version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Виправлено! Nginx за замовчуванням працює на 80 порту
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
